# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.14.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.14.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/apple/CV_Project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/apple/CV_Project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.14.1/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.14.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/apple/CV_Project/CMakeFiles /Users/apple/CV_Project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/apple/CV_Project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named project_cml

# Build rule for target.
project_cml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 project_cml
.PHONY : project_cml

# fast build rule for target.
project_cml/fast:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/build
.PHONY : project_cml/fast

src/ConjGrad.o: src/ConjGrad.cpp.o

.PHONY : src/ConjGrad.o

# target to build an object file
src/ConjGrad.cpp.o:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/src/ConjGrad.cpp.o
.PHONY : src/ConjGrad.cpp.o

src/ConjGrad.i: src/ConjGrad.cpp.i

.PHONY : src/ConjGrad.i

# target to preprocess a source file
src/ConjGrad.cpp.i:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/src/ConjGrad.cpp.i
.PHONY : src/ConjGrad.cpp.i

src/ConjGrad.s: src/ConjGrad.cpp.s

.PHONY : src/ConjGrad.s

# target to generate assembly for a file
src/ConjGrad.cpp.s:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/src/ConjGrad.cpp.s
.PHONY : src/ConjGrad.cpp.s

src/DataCost.o: src/DataCost.cpp.o

.PHONY : src/DataCost.o

# target to build an object file
src/DataCost.cpp.o:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/src/DataCost.cpp.o
.PHONY : src/DataCost.cpp.o

src/DataCost.i: src/DataCost.cpp.i

.PHONY : src/DataCost.i

# target to preprocess a source file
src/DataCost.cpp.i:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/src/DataCost.cpp.i
.PHONY : src/DataCost.cpp.i

src/DataCost.s: src/DataCost.cpp.s

.PHONY : src/DataCost.s

# target to generate assembly for a file
src/DataCost.cpp.s:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/src/DataCost.cpp.s
.PHONY : src/DataCost.cpp.s

src/DigitalMontage.o: src/DigitalMontage.cpp.o

.PHONY : src/DigitalMontage.o

# target to build an object file
src/DigitalMontage.cpp.o:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/src/DigitalMontage.cpp.o
.PHONY : src/DigitalMontage.cpp.o

src/DigitalMontage.i: src/DigitalMontage.cpp.i

.PHONY : src/DigitalMontage.i

# target to preprocess a source file
src/DigitalMontage.cpp.i:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/src/DigitalMontage.cpp.i
.PHONY : src/DigitalMontage.cpp.i

src/DigitalMontage.s: src/DigitalMontage.cpp.s

.PHONY : src/DigitalMontage.s

# target to generate assembly for a file
src/DigitalMontage.cpp.s:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/src/DigitalMontage.cpp.s
.PHONY : src/DigitalMontage.cpp.s

src/GCoptimization.o: src/GCoptimization.cpp.o

.PHONY : src/GCoptimization.o

# target to build an object file
src/GCoptimization.cpp.o:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/src/GCoptimization.cpp.o
.PHONY : src/GCoptimization.cpp.o

src/GCoptimization.i: src/GCoptimization.cpp.i

.PHONY : src/GCoptimization.i

# target to preprocess a source file
src/GCoptimization.cpp.i:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/src/GCoptimization.cpp.i
.PHONY : src/GCoptimization.cpp.i

src/GCoptimization.s: src/GCoptimization.cpp.s

.PHONY : src/GCoptimization.s

# target to generate assembly for a file
src/GCoptimization.cpp.s:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/src/GCoptimization.cpp.s
.PHONY : src/GCoptimization.cpp.s

src/Graph.o: src/Graph.cpp.o

.PHONY : src/Graph.o

# target to build an object file
src/Graph.cpp.o:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/src/Graph.cpp.o
.PHONY : src/Graph.cpp.o

src/Graph.i: src/Graph.cpp.i

.PHONY : src/Graph.i

# target to preprocess a source file
src/Graph.cpp.i:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/src/Graph.cpp.i
.PHONY : src/Graph.cpp.i

src/Graph.s: src/Graph.cpp.s

.PHONY : src/Graph.s

# target to generate assembly for a file
src/Graph.cpp.s:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/src/Graph.cpp.s
.PHONY : src/Graph.cpp.s

src/LinkedBlockList.o: src/LinkedBlockList.cpp.o

.PHONY : src/LinkedBlockList.o

# target to build an object file
src/LinkedBlockList.cpp.o:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/src/LinkedBlockList.cpp.o
.PHONY : src/LinkedBlockList.cpp.o

src/LinkedBlockList.i: src/LinkedBlockList.cpp.i

.PHONY : src/LinkedBlockList.i

# target to preprocess a source file
src/LinkedBlockList.cpp.i:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/src/LinkedBlockList.cpp.i
.PHONY : src/LinkedBlockList.cpp.i

src/LinkedBlockList.s: src/LinkedBlockList.cpp.s

.PHONY : src/LinkedBlockList.s

# target to generate assembly for a file
src/LinkedBlockList.cpp.s:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/src/LinkedBlockList.cpp.s
.PHONY : src/LinkedBlockList.cpp.s

src/MaxFlow.o: src/MaxFlow.cpp.o

.PHONY : src/MaxFlow.o

# target to build an object file
src/MaxFlow.cpp.o:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/src/MaxFlow.cpp.o
.PHONY : src/MaxFlow.cpp.o

src/MaxFlow.i: src/MaxFlow.cpp.i

.PHONY : src/MaxFlow.i

# target to preprocess a source file
src/MaxFlow.cpp.i:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/src/MaxFlow.cpp.i
.PHONY : src/MaxFlow.cpp.i

src/MaxFlow.s: src/MaxFlow.cpp.s

.PHONY : src/MaxFlow.s

# target to generate assembly for a file
src/MaxFlow.cpp.s:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/src/MaxFlow.cpp.s
.PHONY : src/MaxFlow.cpp.s

src/Parser.o: src/Parser.cpp.o

.PHONY : src/Parser.o

# target to build an object file
src/Parser.cpp.o:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/src/Parser.cpp.o
.PHONY : src/Parser.cpp.o

src/Parser.i: src/Parser.cpp.i

.PHONY : src/Parser.i

# target to preprocess a source file
src/Parser.cpp.i:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/src/Parser.cpp.i
.PHONY : src/Parser.cpp.i

src/Parser.s: src/Parser.cpp.s

.PHONY : src/Parser.s

# target to generate assembly for a file
src/Parser.cpp.s:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/src/Parser.cpp.s
.PHONY : src/Parser.cpp.s

src/Util.o: src/Util.cpp.o

.PHONY : src/Util.o

# target to build an object file
src/Util.cpp.o:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/src/Util.cpp.o
.PHONY : src/Util.cpp.o

src/Util.i: src/Util.cpp.i

.PHONY : src/Util.i

# target to preprocess a source file
src/Util.cpp.i:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/src/Util.cpp.i
.PHONY : src/Util.cpp.i

src/Util.s: src/Util.cpp.s

.PHONY : src/Util.s

# target to generate assembly for a file
src/Util.cpp.s:
	$(MAKE) -f CMakeFiles/project_cml.dir/build.make CMakeFiles/project_cml.dir/src/Util.cpp.s
.PHONY : src/Util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... project_cml"
	@echo "... src/ConjGrad.o"
	@echo "... src/ConjGrad.i"
	@echo "... src/ConjGrad.s"
	@echo "... src/DataCost.o"
	@echo "... src/DataCost.i"
	@echo "... src/DataCost.s"
	@echo "... src/DigitalMontage.o"
	@echo "... src/DigitalMontage.i"
	@echo "... src/DigitalMontage.s"
	@echo "... src/GCoptimization.o"
	@echo "... src/GCoptimization.i"
	@echo "... src/GCoptimization.s"
	@echo "... src/Graph.o"
	@echo "... src/Graph.i"
	@echo "... src/Graph.s"
	@echo "... src/LinkedBlockList.o"
	@echo "... src/LinkedBlockList.i"
	@echo "... src/LinkedBlockList.s"
	@echo "... src/MaxFlow.o"
	@echo "... src/MaxFlow.i"
	@echo "... src/MaxFlow.s"
	@echo "... src/Parser.o"
	@echo "... src/Parser.i"
	@echo "... src/Parser.s"
	@echo "... src/Util.o"
	@echo "... src/Util.i"
	@echo "... src/Util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

